### ISSUE TITLE
Small-scale views should show aggregates instead of markers

### ISSUE THREAD

**Issue by sdob** [RuairiK/divesit.es#1]
At small scales (e.g. full-country views) showing map markers for all dive sites in the viewable region presents the user with a lot of visual clutter. It would be better just to show a total - à la "20 sites in this quadrant of the region you're viewing" - until the user zooms in to around Admiralty chart scale.

**Comment by sdob** [comment]
Assume you've checked out https://developers.google.com/maps/articles/toomanymarkers

**Comment by sdob** [comment]
I know that there's a bug in the Angular directive but it could be worked around with pure JS event listening, perhaps.

**Comment by RuairiK** [comment]
It could, but that seems like a messy solution, according to https://github.com/angular-ui/angular-google-maps/issues/1047 it's been fixed on master so I'm going to try downloading the master branch and see if it fixes the issue, it will mean we'll have to manually upgrade the library until the fix is propagated to the bower version.

**Comment by sdob** [comment]
Oh yes, very fresh! Do you want to go ahead and fork them? I kind of feel like we're running out of enhancements to Compass's work :-D

**Comment by RuairiK** [comment]
Actually scratch my last comment, you can force bower to install from master, the bug is fixed and clustering is working I'll push the changes.

**Comment by sdob** [comment]
Lovely job - will sync my repo in the morning.

**Comment by RuairiK** [comment]
My last commits fix this so I'm closing it as completed.
